### ISSUE TITLE
Airport invisible wall

### ISSUE THREAD

**Issue by yukkuri4934** [valentyn-l/GTAIV.EFLC.Various.Fixes#39]
invisible wall here   can not through
![b](https://github.com/user-attachments/assets/2ea6fac9-44cc-4f95-9bbc-87bf3c60e893)

other signbord can through
![a](https://github.com/user-attachments/assets/d838788d-dfc6-47a2-a0a6-acc089bf4dd4)

**Comment by valentyn-l** [comment]
There's no issue with the collision here. What is most likely the issue is the player's collision box which is higher than the model, thus blocking the player from going under. There's not much that can be done about this afaik
![image](https://github.com/user-attachments/assets/fa05958b-7ff5-4507-b3db-3a1744c99e4f)

**Comment by Tomasak** [comment]
![Grand Theft Auto 4 Screenshot 2024 08 03 - 15 51 42 16](https://github.com/user-attachments/assets/150001d1-8148-4675-9689-3d94d1b9a992)
it's already fixed in various fixes tho (for IV only tho, not tlad/tbogt)

**Comment by yukkuri4934** [comment]
I used FF and VF but it didn't solve the problem
I do not know why..>_<
